apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-ldap-ldifs
  labels:
    app.kubernetes.io/part-of: sas-ldap-server
data:
  0-create-domain.ldif: |
    # Include core schema
    dn: cn=schema,cn=config
    changetype: modify
    add: olcInclude
    olcInclude: file:///opt/bitnami/openldap/etc/schema/core.ldif

    # Include cosine schema
    dn: cn=schema,cn=config
    changetype: modify
    add: olcInclude
    olcInclude: file:///opt/bitnami/openldap/etc/schema/cosine.ldif

    # Include inetorgperson schema
    dn: cn=schema,cn=config
    changetype: modify
    add: olcInclude
    olcInclude: file:///opt/bitnami/openldap/etc/schema/inetorgperson.ldif

    # Include rfc2307bis schema (assuming it's available in the specified path)
    dn: cn=schema,cn=config
    changetype: modify
    add: olcInclude
    olcInclude: file:///opt/bitnami/openldap/etc/schema/rfc2307bis.ldif

    # Domain
    dn: dc=sasldap,dc=com
    objectClass: top
    objectClass: domain
    dc: sasldap
  1a-load-memberof-module.ldif: |
    dn: cn=module{0},cn=config
    changetype: modify
    add: olcModuleLoad
    olcModuleLoad: /opt/bitnami/openldap/lib/openldap/memberof.so
  1b-configure-memberof-overlay.ldif: |
    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcMemberOf
    olcOverlay: memberof
    olcMemberOfDangling: ignore
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: groupOfNames
    olcMemberOfMemberAD: member
    olcMemberOfMemberOfAD: memberOf

    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcAccess
    olcAccess: to attrs=memberOf by * read