apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-ldap-ldifs
  labels:
    app.kubernetes.io/part-of: sas-ldap-server
data:
  0-create-domain.ldif: |
    # Domain
    dn: dc=sasldap,dc=com
    objectClass: top
    objectClass: domain
    dc: sasldap

    # OU: service
    dn: ou=service,dc=sasldap,dc=com
    objectClass: organizationalUnit
    objectClass: top
    ou: service
  1a-load-memberof-module.ldif: |
    dn: cn=module{0},cn=config
    changetype: modify
    add: olcModuleLoad
    olcModuleLoad: /opt/bitnami/openldap/lib/openldap/memberof.so
  1b-configure-memberof-overlay.ldif: |
    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcMemberOf
    olcOverlay: memberof
    olcMemberOfDangling: ignore
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: groupOfNames
    olcMemberOfMemberAD: member
    olcMemberOfMemberOfAD: memberOf

    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcAccess
    olcAccess: to attrs=memberOf by * read
  2-create-sasbind.ldif: |
    # User: sasbind
    dn: uid=sasbind,ou=service,dc=sasldap,dc=com
    objectClass: top
    objectClass: person
    objectClass: organizationalPerson
    objectClass: inetOrgPerson
    cn: sasbind
    sn: SAS Bind User
    uid: sasbind
    userPassword: SAS@ldapB1nd
    description: SAS Bind Read-Only User
  #3-sas_ldap_structure.ldif: |
