apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-ldap-memberof-overlay
  labels:
    app.kubernetes.io/part-of: sas-ldap-server
data:
  03-memberOf.ldif: |
    # Load memberof module
    dn: cn=module,cn=config
    changetype: modify
    add: olcModuleLoad
    olcModuleLoad: memberof
    
    # Backend memberOf overlay
    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    changetype: add
    objectClass: olcOverlayConfig
    objectClass: olcMemberOf
    olcOverlay: memberof
    olcMemberOfDangling: ignore
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: posixGroup
    olcMemberOfMemberAD: member
    olcMemberOfMemberOfAD: memberOf
