apiVersion: v1
kind: ConfigMap
metadata:
  name: sas-ldap-ldifs
  labels:
    app.kubernetes.io/part-of: sas-ldap-server
data:
  loadMemberOfModule.ldif: |
    dn: cn=module{0},cn=config
    changetype: modify
    add: olcModuleLoad
    olcModuleLoad: /opt/bitnami/openldap/lib/openldap/memberof.so
  configureMemberOfOverlay.ldif: |
    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcMemberOf
    olcOverlay: memberof
    olcMemberOfDangling: ignore
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: groupOfNames
    olcMemberOfMemberAD: member
    olcMemberOfMemberOfAD: memberOf

    dn: olcDatabase={2}mdb,cn=config
    changetype: modify
    add: olcAccess
    olcAccess: to attrs=memberOf by * read
