---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-ldap-server
  labels:
    app: sas-ldap-server
    app.kubernetes.io/part-of: sas-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sas-ldap-server
  template:
    metadata:
      labels:
        app: sas-ldap-server
        app.kubernetes.io/part-of: sas-ldap
    spec:
      containers:
        - name: sas-ldap-server
          image: antonioneri/openldap:latest
          imagePullPolicy: IfNotPresent
          args:
            - --copy-service
          volumeMounts:
            - name: sas-ldap-volume-overlay
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/03-memberOf.ldif
              subPath: 03-memberOf.ldif
            - name: sas-ldap-db
              mountPath: /var/lib/ldap
            - name: sas-ldap-config
              mountPath: /etc/ldap/slapd.d
            - name: sas-ldap-certs-ca
              mountPath: /container/service/slapd/assets/certs/ca.crt
              subPath: ca.crt
            - name: sas-ldap-certs-crt
              mountPath: /container/service/slapd/assets/certs/tls.crt
              subPath: tls.crt
            - name: sas-ldap-certs-key
              mountPath: /container/service/slapd/assets/certs/tls.key
              subPath: tls.key
          ports:
            - containerPort: 636
              name: sas-ldaps-port
            - containerPort: 3269
              name: sas-ldaps-gport
          env:
            - name: LDAP_TLS
              value: "true"
            - name: LDAP_TLS_CRT_FILENAME
              value: "tls.crt"
            - name: LDAP_TLS_KEY_FILENAME
              value: "tls.key"
            - name: LDAP_TLS_CA_CRT_FILENAME
              value: "ca.crt"
            - name: LDAP_TLS_VERIFY_CLIENT
              value: "never"
            - name: LDAP_ORGANISATION
              value: "SASLDAP"
            - name: LDAP_DOMAIN
              value: "sasldap.com"
            - name: LDAP_ADMIN_PASSWORD
              value: "SAS@ldapAdm1n"
            - name: LDAP_CONFIG_PASSWORD
              value: "SAS@ldapAdm1n"
            - name: LDAP_READONLY_USER
              value: "true"
            - name: LDAP_READONLY_USER_USERNAME
              value: "sasbind"
            - name: LDAP_READONLY_USER_PASSWORD
              value: "SAS@ldapB1nd"
            - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
              value: "false"
            - name: LDAP_RFC2307BIS_SCHEMA
              value: "true"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: sas-ldap-volume-overlay
          configMap:
            name: sas-ldap-memberof-overlay
        - name: sas-ldap-db
          persistentVolumeClaim:
            claimName: sas-ldap-db-pvc
        - name: sas-ldap-config
          persistentVolumeClaim:
            claimName: sas-ldap-config-pvc
        - name: sas-ldap-certs-ca
          secret:
            secretName: "sas-ldap-ca-certificate"
        - name: sas-ldap-certs-crt
          secret:
            secretName: "sas-ldap-certificate"
        - name: sas-ldap-certs-key
          secret:
            secretName: "sas-ldap-certificate"
