apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-ldap-server
  labels:
    app: sas-ldap-server
    app.kubernetes.io/part-of: sas-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sas-ldap-server
  template:
    metadata:
      labels:
        app: sas-ldap-server
        app.kubernetes.io/part-of: sas-ldap
    spec:
      containers:
        - name: sas-ldap-server
          image: bitnami/openldap:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1389
              name: sas-ldap-port
            - containerPort: 1636
              name: sas-ldaps-port
          envFrom:
            - configMapRef:
                name: sas-ldap-config
          volumeMounts:
            - name: sas-ldap-data
              mountPath: /bitnami/openldap/data
            - name: sas-ldap-config
              mountPath: /bitnami/openldap/config
            - name: sas-ldap-certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: sas-ldap-data
          persistentVolumeClaim:
            claimName: sas-ldap-data-pvc
        - name: sas-ldap-config
          persistentVolumeClaim:
            claimName: sas-ldap-config-pvc
        - name: sas-ldap-certs
          secret:
            secretName: sas-ldap-certs
