apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - storage.yaml
  - service.yaml
secretGenerator:
  - name: sas-ldap-certs
    files:
      - ca.crt=certificates/sasldap_CA.crt
      - tls.crt=certificates/sasldap_server.crt
      - tls.key=certificates/sasldap_server.key
configMapGenerator:
  - name: sas-ldap-config
    literals:
      ## Uncomment the line below to enable debug
      - BITNAMI_DEBUG=true
      - LDAP_PORT_NUMBER=1389       # move to deployment.yaml
      - LDAP_LDAPS_PORT_NUMBER=1636 # move to deployment.yaml
      - LDAP_ROOT=dc=sasldap,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=SAS@ldapAdm1n
      - LDAP_ENABLE_TLS=yes
      ## Uncomment the line below to force TLS
      #- LDAP_REQUIRE_TLS=yes
      - LDAP_TLS_CERT_FILE=/certs/tls.crt
      - LDAP_TLS_KEY_FILE=/certs/tls.key
      - LDAP_TLS_CA_FILE=/certs/ca.crt
      - LDAP_EXTRA_SCHEMAS=cosine, inetorgperson # move to deployment.yaml
      - LDAP_CUSTOM_SCHEMA_FILE=/schemas/rfc2307bis.ldif
      #- LDAP_CUSTOM_LDIF_DIR=/ldifs
  - name: sas-ldap-schema
    files:
      - schemas/rfc2307bis.ldif
  #- name: sas-ldap-ldifs
  #  files:
  #    - ldifs/1-memberOf_config.ldif
  #    - ldifs/2-refint1.ldif
  #    - ldifs/3-refint2.ldif