apiVersion: v1
kind: Service
metadata:
  name: sas-ldap-service
  labels:
    app: sas-ldap-server
spec:
  ports:
    - name: sas-ldap-port
      port: $(LDAP_PORT_NUMBER)
      targetPort: $(LDAP_PORT_NUMBER)
    - name: sas-ldaps-port
      port: $(LDAP_LDAPS_PORT_NUMBER)
      targetPort: $(LDAP_LDAPS_PORT_NUMBER)
  selector:
    app: sas-ldap-server
  type: ClusterIP
