apiVersion: v1
kind: Service
metadata:
  name: sas-ldap-service
  labels:
    app: sas-ldap-server
spec:
  type: LoadBalancer # default is ClusterIP
  selector:
    app: sas-ldap-server
  ports:
    - name: sas-ldap-port
      port: 1389
      targetPort: 1389
      protocol: TCP
    - name: sas-ldaps-port
      port: 1636
      targetPort: 1636
      protocol: TCP