apiVersion: v1
kind: Service
metadata:
  name: sas-ldap-service
  labels:
    app: sas-ldap-server
spec:
  selector:
    app.kubernetes.io/name: sas-ldap-server
  type: ClusterIP
  #sessionAffinity: None
  #sessionAffinityConfig:
  #  clientIP:
  #    timeoutSeconds: 10800
  ports:
    - name: sas-ldap-port
      port: 1389
      targetPort: 1389
    - name: sas-ldaps-port
      port: 1636
      targetPort: 1636
