---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-ldap-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: desiredStorageClass  ## If commented and undefined, if will use the default one.
  resources:
    requests:
      storage: 1Gi   # Adjust the size as per your requirement
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-ldap-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: desiredStorageClass  ## If commented and undefined, if will use the default one.
  resources:
    requests:
      storage: 1Gi   # Adjust the size as per your requirement
