#!/usr/bin/python3 -u
# -*- coding: utf-8 -*-

import os
import shutil
import argparse
import sys

IMPORT_SERVICE_DIR = "/container/service"
RUN_SERVICE_DIR = "/container/run/service"

def copy_service_to_run_dir():
    if os.path.exists(RUN_SERVICE_DIR):
        print(f"Copy {IMPORT_SERVICE_DIR} to {RUN_SERVICE_DIR} ignored", file=sys.stderr)
        print(f"{RUN_SERVICE_DIR} already exists", file=sys.stderr)
        return

    print(f"Copy {IMPORT_SERVICE_DIR} to {RUN_SERVICE_DIR}")
    try:
        shutil.copytree(IMPORT_SERVICE_DIR, RUN_SERVICE_DIR)
    except shutil.Error as e:
        print(f"Error copying service directory: {e}", file=sys.stderr)

def main():
    parser = argparse.ArgumentParser(description='Copy service directory to run directory.')
    parser.add_argument('--copy-service', action='store_true', help='Copy service directory to run directory.')
    args = parser.parse_args()

    if args.copy_service:
        copy_service_to_run_dir()

if __name__ == "__main__":
    main()
