apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas-ldap-server
  labels:
    app: sas-ldap-server
    app.kubernetes.io/part-of: sas-ldap
spec:
  selector:
    matchLabels:
      app: sas-ldap-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sas-ldap-server
        app.kubernetes.io/part-of: sas-ldap-server
    spec:
      containers:
        - name: sas-ldap-server
          image: sas-ldap-server:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 1389
              name: sas-ldap-port
            - containerPort: 1636
              name: sas-ldaps-port
          envFrom:
            - configMapRef:
                name: sas-ldap-config
          volumeMounts:
            - name: sas-ldap-data
              mountPath: /bitnami
      volumes:
        - name: sas-ldap-data
          persistentVolumeClaim:
            claimName: sas-ldap-data-pvc
      restartPolicy: Always
