apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - storage.yaml
  - service.yaml

images:
  - name: sas-ldap-server
    newName: antonioneri/sas-openldap
    newTag: latest
